export type ReportType = 
  | "plantation-summary"
  | "task-performance"
  | "financial-summary"
  | "inventory-report"
  | "sustainability-report"
  | "yield-forecast";

export type ReportSection = {
  title: string;
  content: string | Record<string, unknown>;
  type: "text" | "table" | "chart" | "metrics";
};

export type Report = {
  id: string;
  type: ReportType;
  title: string;
  generatedAt: Date;
  generatedBy?: string;
  sections: ReportSection[];
  summary?: string;
};

export const generatePlantationSummary = (plantations: unknown[]): ReportSection[] => {
  return [
    {
      title: "Overview",
      content: `Total Plantations: ${plantations.length}`,
      type: "metrics",
    },
    {
      title: "Details",
      content: JSON.stringify(plantations, null, 2),
      type: "table",
    },
  ];
};

export const generateTaskPerformance = (tasks: unknown[]): ReportSection[] => {
  const completed = Array.isArray(tasks)
    ? tasks.filter((t: unknown) => (t as { status?: string }).status === "completed").length
    : 0;
  const total = Array.isArray(tasks) ? tasks.length : 0;
  const completionRate = total > 0 ? (completed / total) * 100 : 0;

  return [
    {
      title: "Performance Metrics",
      content: {
        totalTasks: total,
        completedTasks: completed,
        completionRate: `${completionRate.toFixed(1)}%`,
      },
      type: "metrics",
    },
    {
      title: "Task Details",
      content: JSON.stringify(tasks, null, 2),
      type: "table",
    },
  ];
};

export const generateFinancialSummary = (transactions: unknown[]): ReportSection[] => {
  const total = Array.isArray(transactions)
    ? transactions.reduce((sum: number, t: unknown) => {
        const amount = (t as { amount?: number }).amount || 0;
        return sum + amount;
      }, 0)
    : 0;

  return [
    {
      title: "Financial Overview",
      content: {
        totalTransactions: Array.isArray(transactions) ? transactions.length : 0,
        totalAmount: total,
        currency: "USD",
      },
      type: "metrics",
    },
  ];
};

export const createReport = (
  type: ReportType,
  data: unknown[],
  generatedBy?: string
): Report => {
  let sections: ReportSection[] = [];
  let title = "";

  switch (type) {
    case "plantation-summary":
      title = "Plantation Summary Report";
      sections = generatePlantationSummary(data);
      break;
    case "task-performance":
      title = "Task Performance Report";
      sections = generateTaskPerformance(data);
      break;
    case "financial-summary":
      title = "Financial Summary Report";
      sections = generateFinancialSummary(data);
      break;
    default:
      title = "Custom Report";
      sections = [
        {
          title: "Data",
          content: JSON.stringify(data, null, 2),
          type: "table",
        },
      ];
  }

  return {
    id: `report-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type,
    title,
    generatedAt: new Date(),
    generatedBy,
    sections,
  };
};

export const exportReportToPdf = (report: Report): void => {
  const content = `
    <html>
      <head>
        <title>${report.title}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 20px; }
          h1 { color: #8B4513; }
          h2 { color: #654321; margin-top: 20px; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; }
          th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
          th { background-color: #8B4513; color: white; }
        </style>
      </head>
      <body>
        <h1>${report.title}</h1>
        <p>Generated: ${report.generatedAt.toLocaleString()}</p>
        ${report.sections.map((section) => `
          <h2>${section.title}</h2>
          <pre>${typeof section.content === "string" ? section.content : JSON.stringify(section.content, null, 2)}</pre>
        `).join("")}
      </body>
    </html>
  `;

  const blob = new Blob([content], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${report.title.replace(/\s+/g, "-")}.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const formatReportAsText = (report: Report): string => {
  let text = `${report.title}\n`;
  text += `Generated: ${report.generatedAt.toLocaleString()}\n`;
  if (report.generatedBy) {
    text += `Generated By: ${report.generatedBy}\n`;
  }
  text += "\n";

  report.sections.forEach((section) => {
    text += `${section.title}\n`;
    text += "=".repeat(section.title.length) + "\n";
    if (typeof section.content === "string") {
      text += section.content + "\n";
    } else {
      text += JSON.stringify(section.content, null, 2) + "\n";
    }
    text += "\n";
  });

  return text;
};

